name: Go

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go: [ "1.24" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Test build (non-Windows)
        if: matrix.os != 'windows-latest'
        run: |
          CGO_ENABLED=0 go build main.go
      - name: Test build (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          $env:CGO_ENABLED = '0'
          go build main.go